### PR TITLE
fix: Reduce lock contention in Lake Cache

### LINKED ISSUE #419: Reduce duplicate Lake requests across dedicated streams
After https://github.com/near/queryapi/issues/418, each Indexer will have it's own dedicated 'real-time' stream, creating many duplicate requests to NEAR Lake. These duplicate requests should be reduced.

One approach is to use a singleton Lake client, which ensures only a single request is sent per block, and awaits the existing one otherwise. But I'm not entirely sure how this can be implemented.

### PR DESCRIPTION
**Pull request by morgsmccauley**
This PR addresses significant lock contention issues within the Lake Cache by replacing the `tokio::sync::Mutex` with `std::sync::Mutex`. The use of an asynchronous mutex exacerbated contention in our highly concurrent environment. Specifically, `tokio::sync::Mutex` yielding when the lock is unavailable, leads to all tasks requiring the lock to enter a repetitive cycle of acquisition attempts, failures, and subsequent yields. When the lock becomes available, all waiting tasks wake simultaneously, attempt to re-acquire the lock, and yield again if unsuccessful. This behaviour results in substantial scheduling overhead.

Switching to `std::sync::Mutex` alters this dynamic by blocking the thread attempting to acquire the lock, rather than merely yielding control. This change simplifies the lock acquisition process by eliminating the need to wake multiple tasks. Instead, the OS scheduler directly allocates the lock to one of the waiting threads when it becomes available. This approach reduces the complexity and overhead introduced by the task scheduler, enhancing performance and reliability under high contention.

### CODE REVIEW

File: block-streamer/src/lake_s3_client.rs [hunk 1]
```diff
@@ -77,12 +77,19 @@ impl FuturesCache {
...
+    fn lock(&self) -> MutexGuard<'_, SizedCache<String, SharedGetObjectBytesFuture>> {
         let timer = metrics::LAKE_CACHE_LOCK_WAIT_SECONDS.start_timer();
 
-        let lock = self.cache.lock().await;
+        let lock = match self.cache.lock() {
+            Ok(lock) => lock,
+            Err(poisoned) => {
+                let lock = poisoned.into_inner();
+
+                tracing::error!("Lake Cache Mutex was poisoned, recovering...");
```
Comment (darunrs) [inline block-streamer/src/lake_s3_client.rs:88]: Just curious, what sort of scenario would lead to a lock throwing an error like this?

File: block-streamer/src/lake_s3_client.rs [hunk 2]
```diff
@@ -77,12 +77,19 @@ impl FuturesCache {
...
+
+                lock
```
Comment (darunrs) [inline block-streamer/src/lake_s3_client.rs:90]: So we still return the lock? Is the intention to simply log the error but proceed? Why does the lock still work?

**Review by darunrs — APPROVED** [review]
Nice solution!

File: block-streamer/src/lake_s3_client.rs (hunk 1 above)
Comment (morgsmccauley) [reply block-streamer/src/lake_s3_client.rs:88]: > If another user of this mutex panicked while holding the mutex, then
this call will return an error once the mutex is acquired.

from the docs

File: block-streamer/src/lake_s3_client.rs (hunk 2 above)
Comment (morgsmccauley) [reply block-streamer/src/lake_s3_client.rs:90]: Yeah, another thread panicing while still holding the lock isn't really an issue. The cache wouldn't necessarily be in a bad state so we can still operate on it.
