### PR TITLE
fix: Remove role restriction for removing functions

### LINKED ISSUE #822: Unable to delete Indexer after publishing
We've removed the whitelist restrictions for publishing Indexers, but they still exist for deletion. The restrictions should also be removed from delete.

image

### PR DESCRIPTION
**Pull request by morgsmccauley**
Also runs `cargo format` (1st commit)

closes: #822

### CODE REVIEW

**Comment by morgsmccauley** [comment]
Deployed to both dev/prod contracts

File: registry/contract/src/lib.rs [hunk 1]
```diff
@@ -329,10 +329,7 @@ impl Contract {
                     env::panic_str(&format!("Account ID {} is invalid", account_id));
                 })
             }
-            None => {
-                self.assert_roles(vec![Role::Owner, Role::User]);
-                env::signer_account_id()
-            }
+            None => env::signer_account_id(),
```
Comment (gabehamilton) [inline registry/contract/src/lib.rs:332]: Would also be useful if owner's could remove any indexer; large suspended indexers for instance.

Comment (morgsmccauley) [reply registry/contract/src/lib.rs:332]: They can - if `account_id` is specified, we'll only permit the tx if the signer is `Owner`
