### PR TITLE
fix: Various Control Plane migration fixes

### LINKED ISSUE #520: Migrate Indexers to Control Plane
Indexers should either run on Coordinator V1 or V2, and a process needs to be set up to migrate these indexers across. This work should build on top of the existing `allowlist`.

For a given account, the flow will roughly be:
1. Coordinator V1 ignores accounts within the `allowlist` and sets the `v1_ack` - we need an acknowledge to ensure V2 doesn't start before V1 stopped
2. Coordinator V2 starts indexers within the `allowlist` which have the `v1_ack` set
3. Coordinator V2:
    1. Remove the indexer from the `streams` Redis Set, preventing Runner from starting it again
    2. Stop the current historical/real-time executors
    3. Move all messages from the historical/real-time streams to a new single stream
    4. Using the stream above, start a Block Stream from last_published_block, and start the corresponding Executor
    5. Set the `migration_complete` flag to prevent the migration from running again

### PR DESCRIPTION
**Pull request by morgsmccauley**

### CODE REVIEW

File: coordinator/src/redis.rs [hunk 1]
```diff
@@ -34,16 +34,17 @@ impl RedisClientImpl {
         })
     }
 
-    pub async fn get<T, U>(&self, key: T) -> anyhow::Result<U>
+    pub async fn get<T, U>(&self, key: T) -> anyhow::Result<Option<U>>
```
Comment (morgsmccauley) [inline coordinator/src/redis.rs:37]: Not actually directly related, but quite a nice change to have

File: indexer/queryapi_coordinator/src/main.rs [hunk 2]
```diff
@@ -43,10 +43,14 @@ pub(crate) struct QueryApiContext<'a> {
     pub redis_url: &'a str,
 }
 
+// TODO add missing keys to prevent deserialization error on v2 side
 #[derive(serde::Deserialize, serde::Serialize, Debug)]
 struct DenylistEntry {
     account_id: AccountId,
     v1_ack: bool,
+    migrated: bool,
```
Comment (morgsmccauley) [inline indexer/queryapi_coordinator/src/main.rs:51]: This can still be deserialized without these fields, but it means they will be removed when serializing again.

File: coordinator/src/migration.rs [hunk 3]
```diff
@@ -104,8 +113,7 @@ async fn migrate_account(
             .context("Failed to merge streams")?;
     }
 
-    // TODO Uncomment when V2 correctly continues from V1 stop point
-    // set_migrated_flag(redis_client, account_id)?;
+    set_migrated_flag(redis_client, account_id)?;
```
Comment (morgsmccauley) [inline coordinator/src/migration.rs:116]: We need to set the `migrated` flag to prevent further attempts to migrate

File: coordinator/src/migration.rs [hunk 4]
```diff
@@ -14,12 +14,17 @@ pub struct AllowlistEntry {
     v1_ack: bool,
     migrated: bool,
     failed: bool,
+    v2_control: bool,
```
Comment (morgsmccauley) [inline coordinator/src/migration.rs:17]: Since we have to set the `migrated` flag, this allows us to still prevent V2 from taking control. Providing time to sanity check the migration itself.

**Comment by morgsmccauley** [comment]
Going to merge these to unblock testing - feel free to review in retrospect
