### PR TITLE
fix: Require exact config response for lifecycle transitions

### LINKED ISSUE #940: Update contract to return specific data when fetching deleted indexer
Deploy change to contract which has it return data instead of null for a matched indexer which was deleted.

### LINKED ISSUE #941: Add Status Code and content check for indexer config fetch
Coordinator's lifecycle polls the contract for indexer config through RPC. The response for a no match case is null. We handled this as "The indexer was deleted", which is not incorrect. However, it was possible for the call to successfully return with an incorrect null response. As a result, lifecycle would erroneously enter its indexer deletion workflow, which is not reversible. 

This PR takes advantage of contract updates to now expect a response from the contract when an indexer is deleted, rather than expecting a null response for the same.

### PR DESCRIPTION
**Pull request by darunrs**
We've noticed that it is occasionally possible for the indexer config returned by the contract to be parseable/null with a success status code, even though the indexer itself was not in fact deleted. This triggers the deprovisioning workflow anyway, which currently throws the Indexer into a repairing state, where it is no longer operating. 

This PR updates the contract to retain configuration if the indexer was deleted. Coordinator will now expect a specific configuration to take deletion actions, instead of the previous method which left things open to interpretation.

In the near future, the contract will be migrated (#964) to use an enum instead of contract format, to avoid wastefully storing things like code/schema for deleted indexers forever.

### CODE REVIEW

File: coordinator/src/indexer_config.rs [hunk 1]
```diff
@@ -13,6 +13,7 @@ pub struct IndexerConfig {
     pub rule: Rule,
     pub updated_at_block_height: Option<u64>,
     pub created_at_block_height: u64,
+    pub deleted_at_block_height: Option<u64>,
 }
```
Comment (darunrs) [inline coordinator/src/indexer_config.rs:17]: I get the idea of having an indexer config redefined here so that we have helper functions. But, it does lead to duplication of attribute definitions. I wonder if there's a way to make this a new type with registry's IndexerConfig inside it? Like a `IndexerLifecycleConfig` or something. Decided not to mess with it in this PR for now though. Would like to get your thoughts.

File: registry/contract/src/lib.rs [hunk 2]
```diff
@@ -275,7 +273,7 @@ impl Contract {
         let account_indexers =
             self.registry
                 .entry(account_id.clone())
-                .or_insert(IndexerConfigByFunctionName::new(StorageKeys::AccountV3(
```
Comment (darunrs) [inline registry/contract/src/lib.rs:278]: So apparently register was inserting using V3's hash this whole time... I don't know how this will impact migration. Hopefully it goes fine?

File: registry/contract/src/lib.rs [hunk 3]
```diff
@@ -359,11 +357,12 @@ impl Contract {
     pub fn list_by_account(&self, account_id: AccountId) -> AccountIndexers {
         self.registry
             .get(&account_id)
-            .unwrap_or(&IndexerConfigByFunctionName::new(StorageKeys::AccountV3(
+            .unwrap_or(&IndexerConfigByFunctionName::new(StorageKeys::AccountV4(
```
Comment (darunrs) [inline registry/contract/src/lib.rs:360]: Should this actually be V5?

**Review by morgsmccauley — APPROVED** [review]

**Comment by darunrs** [comment]
Verified that register and remove work as expected with actual contract. The code should be good to go.
