### PR TITLE
fix: added polling to latest indexer block height

### LINKED ISSUE #820: Block lag shows incorrect values during live update
The live updates to the Block Lag (`Indexer is X blocks or Y behind the blockchain tip`) incorrectly grows in value, even when the actual block lag is reducing. On fresh load, and refresh, the value appears to be correct, but it becomes incorrect after the live updates.

image

### PR DESCRIPTION
**Pull request by Kevin101Zhang**
props.indexerBlockHeight is static and fetches from GQL. added functionality to update the current Indexer blockheight.

### CODE REVIEW

File: frontend/src/components/Logs/LogsMenu.tsx [hunk 1]
```diff
@@ -67,6 +67,37 @@ const LogsMenu: React.FC<LogsMenuProps> = ({
     }
   }, [attributeMap]);
 
+  useEffect(() => {
```
Comment (morgsmccauley) [inline frontend/src/components/Logs/LogsMenu.tsx:70]: This is basically the same as the two `useEffect`s above. Why don't we just set an interval to call `refetch()`.  `useQuery()` would then return the latest `data`, and the above `useEffect`s would then trigger and update the status/block height.

But this functionality is already built in to `useQuery`, so let's just remove set a [polling interval](https://www.apollographql.com/docs/react/data/queries#polling), and then just rely on the existing `useEffect`s

**Comment by morgsmccauley** [comment]
We should be using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for our PR titles, can you please update yours.

**Review by morgsmccauley — APPROVED** [review]
